export{ default as Home }from "./Home"
export{default as Links}from "./Links"
export{default as Viewnotfound } from "./Viewnotfound"
export{default as About}from "./About"
export{default as Budget}from "./Budget"
export{default as ContactPage}from"./Contact"
export{default as Disclaimer}from "./Disclaimer"
export{default as Balanceabudget}from "./Balanceabudget"
export{default as Howtochangeatire}from "./Howtochangeatire"
export{default as HowToTieATie}from "./HowToTieATie"
export{default as schedule}from "./schedule"
export{default as Whatdoidowhenigetarrested}from "./WhatDoIdowhenIGetArrested"
export{default as Whatdoidowhenilosesomeoneclosetome}from "./WhatdoIdowhenilosesomeoneclosetome"
export{default as WhenAndHowToChangeYourOil}from"./WhenAndHowToChangeYourOil"

