export{ default as Home }from "./Home"
export{default as Viewnotfound } from "./Viewnotfound"
export{default as AboutPage}from "./About"
export{default as BudgetPage}from "./Budget"
export{default as ContactPage}from "./Contact"
export{default as DisclaimerPage}from "./Disclaimer"
export{default as HowToBalanceABudget}from "./Balanceabudget"
export{default as HowToChangeATire}from "./Changeatire"
export{default as HowToTieATie}from "./Tieatie"
export{default as schedulePage}from "./Schedule"
export{default as WhatDoIDoWhenIGetArrested}from "./Whatdoidowhenigetarrested"
export{default as WhatDoIDoWhenILoseSomeoneCloseToMe}from "./WhatdoidowhenIlosesomeoneclosetome"
export{default as WhenAndHowToChangeYourOil}from"./Whenandhowtochangeyouroil"
