export{ default as Home }from "./Home"
export{default as Viewnotfound } from "./Viewnotfound"
export{default as About}from "./About"
export{default as Budget}from "./Budget"
export{default as Contact}from "./Contact"
export{default as Disclaimer}from "./Disclaimer"
export{default as Balanceabudget}from "./Balanceabudget"
export{default as Changeatire}from "./Changeatire"
export{default as Tieatie}from "./Tieatie"
export{default as schedule}from "./Schedule"
export{default as Whatdoidowhenigetarrested}from "./Whatdoidowhenigetarrested"
export{default as WhatdoidowheniLosesomeoneclosetome}from "./WhatdoidowhenIlosesomeoneclosetome"
export{default as Whenandhowtochangeyouroil}from"./Whenandhowtochangeyouroil"
